server:
  port: 8082
    
# MySql #
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/miniveldeingles
    username: admin
    password: gNVnKmZBD9w3ZnH
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Registry Client

eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# URL wordpress
url:
  Wordpress: https://paginanuevadev.colomboamericano.edu.co/wp-json/cael/

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"