server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/sofi_development/colombo-api_miniveldeingles.git
          search-paths:
          - ms-admin-data-server
          username: FabianBahamon
          password: glpat--pAy32Z-osBB-bUxNYpB
          cloneOnStart: true