server:
  port: 8888
spring:
  application:
    name: ms-admin-config-server
#Local configuration for Fabian Bahamon Computer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/admin/Documents/Smarthink/Colombo/Colombo_Backend/ms-admin-data-server
